apiVersion: v1
kind: Secret
metadata:
  name: twitter-secrets
type: Opaque
stringData:
  api_key: "7sGfu9aCIgdbGq46uDdDv7tyx"
  api_secret: "ZdPOoeYSlRwyUPiNIROW8bTenBwdHXCeb9LkXJfwAuj0jasqdB"
  access_token: "1362235623403307008-O1twpV0BrskqC0j6zKVYtHAyQQveE8"
  access_secret: "P4HHJvRqqkK45sZemUDY4rJLM15no3fUfSd3wHPwKOCi3"
